generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Plantilla
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Plantilla
    plural:                Plantillas
    route_prefix:          plantilla
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new: { label: "Crear Nueva Plantilla" }
        _edit: { label: "Editar" }
        _delete: { label: "Eliminar" }
        imprimir: { label: "Imprimir" }
      fields:
        nombre:       { label: Nombre}
      list:
        title:          Plantillas
        batch_actions:
          _delete:      ~
          _imprimir:    ~