generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Plantilla
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Plantilla
    plural:                Plantillas
    route_prefix:          plantilla
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new: { label: "Crear Nueva Plantilla" }
        _edit: { label: "Editar" }
        _delete: { label: "Eliminar" }
        imprimir: { label: "Imprimir" }
      fields:
        nombre:       { label: Nombre}
        created_at:   { label: Fecha de Creacion}
      list:
        fields:
          nombre:       { label: Nombre}
          created_at:   { label: Fecha de Creacion}
        title:          Plantillas
        batch_actions:
          _delete:      ~
          imprimir:    ~
        display:      [nombre, parametros, created_at]
        max_per_page:   5
        sort:           [nombre, asc]
      filter:
        display:        [nombre]
      form:    ~
      edit:
        title:          Editando la Plantilla "%%nombre%%"
        display:        [nombre]
      new:
        display:        [nombre, parametros]
        title:          Nueva Plantilla