<?php

/**
 * BasePlantillas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $clientes_id
 * @property string $contactos_id
 * 
 * @method integer    get()             Returns the current record's "id" value
 * @method string     get()             Returns the current record's "nombre" value
 * @method string     get()             Returns the current record's "clientes_id" value
 * @method string     get()             Returns the current record's "contactos_id" value
 * @method Plantillas set()             Sets the current record's "id" value
 * @method Plantillas set()             Sets the current record's "nombre" value
 * @method Plantillas set()             Sets the current record's "clientes_id" value
 * @method Plantillas set()             Sets the current record's "contactos_id" value
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlantillas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_plantillas');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('clientes_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('contactos_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}