<?php

/**
 * BaseClientes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $nombre_tag
 * @property string $telefono
 * @property string $email
 * @property string $direccion
 * @property Doctrine_Collection $Contactos
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method string              getNombreTag()  Returns the current record's "nombre_tag" value
 * @method string              getTelefono()   Returns the current record's "telefono" value
 * @method string              getEmail()      Returns the current record's "email" value
 * @method string              getDireccion()  Returns the current record's "direccion" value
 * @method Doctrine_Collection getContactos()  Returns the current record's "Contactos" collection
 * @method Clientes            setId()         Sets the current record's "id" value
 * @method Clientes            setNombre()     Sets the current record's "nombre" value
 * @method Clientes            setNombreTag()  Sets the current record's "nombre_tag" value
 * @method Clientes            setTelefono()   Sets the current record's "telefono" value
 * @method Clientes            setEmail()      Sets the current record's "email" value
 * @method Clientes            setDireccion()  Sets the current record's "direccion" value
 * @method Clientes            setContactos()  Sets the current record's "Contactos" collection
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_clientes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nombre_tag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contactos', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}