<?php

/**
 * BaseRemitentes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $direccion
 * @property string $telefono
 * @property string $ciudad
 * 
 * @method integer    get()          Returns the current record's "id" value
 * @method string     get()          Returns the current record's "nombre" value
 * @method string     get()          Returns the current record's "direccion" value
 * @method string     get()          Returns the current record's "telefono" value
 * @method string     get()          Returns the current record's "ciudad" value
 * @method Remitentes set()          Sets the current record's "id" value
 * @method Remitentes set()          Sets the current record's "nombre" value
 * @method Remitentes set()          Sets the current record's "direccion" value
 * @method Remitentes set()          Sets the current record's "telefono" value
 * @method Remitentes set()          Sets the current record's "ciudad" value
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRemitentes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_remitentes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ciudad', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}