<?php

/**
 * BaseRemitente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $direccion
 * @property string $telefono
 * @property string $ciudad
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method string    getNombre()    Returns the current record's "nombre" value
 * @method string    getDireccion() Returns the current record's "direccion" value
 * @method string    getTelefono()  Returns the current record's "telefono" value
 * @method string    getCiudad()    Returns the current record's "ciudad" value
 * @method Remitente setId()        Sets the current record's "id" value
 * @method Remitente setNombre()    Sets the current record's "nombre" value
 * @method Remitente setDireccion() Sets the current record's "direccion" value
 * @method Remitente setTelefono()  Sets the current record's "telefono" value
 * @method Remitente setCiudad()    Sets the current record's "ciudad" value
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRemitente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('remitente');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ciudad', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'options' => 
              array(
              'notnull' => false,
              'required' => false,
              ),
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'options' => 
              array(
              'notnull' => false,
              'required' => false,
              ),
             ),
             ));
        $this->actAs($timestampable0);
    }
}