<?php

/**
 * BaseCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $nombre_tag
 * @property string $telefono
 * @property string $email
 * @property string $direccion
 * @property Doctrine_Collection $Contacto
 * @property Doctrine_Collection $Cliente
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method string              getNombreTag()  Returns the current record's "nombre_tag" value
 * @method string              getTelefono()   Returns the current record's "telefono" value
 * @method string              getEmail()      Returns the current record's "email" value
 * @method string              getDireccion()  Returns the current record's "direccion" value
 * @method Doctrine_Collection getContacto()   Returns the current record's "Contacto" collection
 * @method Doctrine_Collection getCliente()    Returns the current record's "Cliente" collection
 * @method Cliente             setId()         Sets the current record's "id" value
 * @method Cliente             setNombre()     Sets the current record's "nombre" value
 * @method Cliente             setNombreTag()  Sets the current record's "nombre_tag" value
 * @method Cliente             setTelefono()   Sets the current record's "telefono" value
 * @method Cliente             setEmail()      Sets the current record's "email" value
 * @method Cliente             setDireccion()  Sets the current record's "direccion" value
 * @method Cliente             setContacto()   Sets the current record's "Contacto" collection
 * @method Cliente             setCliente()    Sets the current record's "Cliente" collection
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nombre_tag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contacto', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Etiqueta as Cliente', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'options' => 
              array(
              'notnull' => false,
              'required' => false,
              ),
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'options' => 
              array(
              'notnull' => false,
              'required' => false,
              ),
             ),
             ));
        $this->actAs($timestampable0);
    }
}