<?php

/**
 * BasePlantilla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $parametros
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getNombre()     Returns the current record's "nombre" value
 * @method string    getParametros() Returns the current record's "parametros" value
 * @method Plantilla setId()         Sets the current record's "id" value
 * @method Plantilla setNombre()     Sets the current record's "nombre" value
 * @method Plantilla setParametros() Sets the current record's "parametros" value
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlantilla extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plantilla');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('parametros', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'options' => 
              array(
              'notnull' => false,
              'required' => false,
              ),
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'options' => 
              array(
              'notnull' => false,
              'required' => false,
              ),
             ),
             ));
        $this->actAs($timestampable0);
    }
}