<?php

/**
 * BaseContactos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cliente_id
 * @property string $nombre
 * @property string $funcion
 * @property string $cargo
 * @property Clientes $Clientes
 * 
 * @method integer   get()           Returns the current record's "id" value
 * @method integer   get()           Returns the current record's "cliente_id" value
 * @method string    get()           Returns the current record's "nombre" value
 * @method string    get()           Returns the current record's "funcion" value
 * @method string    get()           Returns the current record's "cargo" value
 * @method Clientes  get()           Returns the current record's "Clientes" value
 * @method Contactos set()           Sets the current record's "id" value
 * @method Contactos set()           Sets the current record's "cliente_id" value
 * @method Contactos set()           Sets the current record's "nombre" value
 * @method Contactos set()           Sets the current record's "funcion" value
 * @method Contactos set()           Sets the current record's "cargo" value
 * @method Contactos set()           Sets the current record's "Clientes" value
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_contactos');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('cliente_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('funcion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cargo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Clientes', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}