# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    #robots:       index, follow

  stylesheets:    [bootstrap.css]

  javascripts:    [jquery-1.11.3.min.js, rsvp-3.1.0.min.js, sha-256.min.js, qz-tray.js, bootstrap.min.js, includes.js]

  has_layout:     true
  layout:         layout
