<?php

/**
 * Etiqueta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Etiqueta extends BaseEtiqueta
{
    public function __toString()
    {
      return $this->getNombre();
    }
    
    public function getClienteNombre(){
      $cliente = new Cliente();
      $nombre = $cliente->getNombre();
      return $nombre; 
    }

    public function getContactoNombre(){
      $contacto = new Contacto();
      $nombre = $contacto->getNombre(); 
      return $nombre; 
    }

}