<?php

/**
 * PlantillaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantillaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantillaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plantilla');
    }
}