<?php

/**
 * Plantilla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Plantilla extends BasePlantilla
{
	public function __toString()
  	{
    	return $this->getNombre();
  	}

	public function Imprimir($ids){	
		// Obtiene la fecha
		$now = date('Y-m-d h:i:s A', time());
		// Asigna Ids a Parametros
		$parametros = implode(',', $ids);
		// Nombre Temporal
		$nombre = 'Plantilla '; 		
		// Asigna valores a modelo
		$this->setNombre($nombre.$now);
		$this->setParametros($parametros);
		$this->setUpdatedAt($now);		
		$this->save();
		return true;
	}

}