<?php

/**
 * Plantilla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zebra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Plantilla extends BasePlantilla
{
	public function __toString()
  	{
    	return $this->getNombre();
  	}

	public function Imprimir($ids){
		
		$parametros = implode(',', $ids);

		$this->setNombre('Test');
		$this->setParametros($parametros);
		$now = date('Y-m-d h:i:s', time());
		$this->setUpdatedAt($now);		
		$this->save();
		//return true;
	}

	public function getCliente(){
		$cliente = new Cliente();
		$cliente->getNombre(); 
		return $nombre;
	}
}