<?php

/**
 * PlantillasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantillasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantillasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plantillas');
    }
}