<?php

/**
 * RemitenteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RemitenteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RemitenteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Remitente');
    }
}