<?php

/**
 * RemitentesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RemitentesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RemitentesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Remitentes');
    }
}