# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Zebra Printing
    description:  symfony project
    keywords:     symfony, project
    language:     es
    robots:       index, follow

  stylesheets:    [bootstrap-grid.css, bootstrap.min.css, bootstrap.css, main.css, jquery.modal.css]

  javascripts:    [jquery.js, jquery.min.js, bootstrap.bundle.js, bootstrap.bundle.min.js, bootstrap.js, bootstrap.min.js, includes.js]

  has_layout:     true
  layout:         layout
