generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Remitente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          remitente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new: { label: "Crear Nuevo Remitente" }
        _edit: { label: "Editar" }
        _delete: { label: "Eliminar" }
      fields:
        nombre:       { label: Nombre}
      list:
        title:          Remitentes
        display:        [nombre, direccion, telefono, ciudad]
        max_per_page:   5
        sort:           [nombre, asc]
      filter:
        display:        [nombre, direccion, telefono, ciudad]
      form:    ~
      edit:
        title:          Editando el Remitente "%%nombre%%"
        display:        [nombre, direccion, telefono, ciudad]
      new:
        display:        [nombre, direccion, telefono, ciudad]
        title:          Nuevo Remitente
