Cliente:
  actAs: [Timestampable]
  tableName: cliente
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    nombre:   string(255), notnull: true
    nombre_tag:   string(255), notnull: true
    telefono:  string(255), notnull: true
    email:   string(255), notnull: true
    direccion: string(255), notnull: true
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false
      updated:
        name: updated_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false

Contacto:
  actAs: [Timestampable]
  tableName: contacto
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    cliente_id: integer
    nombre: string(255), notnull: true
    funcion: string(255), notnull: true
    cargo: string(255), notnull: true
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false
      updated:
        name: updated_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false
  relations:
    Cliente:
      class: Cliente
      local: cliente_id
      foreign: id
      foreignAlias: Contacto
      type: one
      foreignType: many

Remitente:
  actAs: [Timestampable]
  tableName: remitente
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    nombre:   string(255), notnull: true
    direccion:   string(255), notnull: true
    telefono:   string(255), notnull: true
    ciudad:   string(255), notnull: true
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false
      updated:
        name: updated_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false

Etiqueta:
  actAs: [Timestampable]
  tableName: etiqueta
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    nombre:   string(255), notnull: true
    cliente_id: string(255), notnull: true
    contacto_id: string(255), notnull: true
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false
      updated:
        name: updated_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false
  relations:
    Cliente:
      class: Cliente
      local: cliente_id
      foreign: id
      foreignAlias: Cliente
      type: one
      foreignType: many
    Contacto:
      class: Contacto
      local: contacto_id
      foreign: id
      foreignAlias: Contacto
      type: one
      foreignType: many

Plantilla:
  actAs: [Timestampable]
  tableName: plantilla
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    nombre:   string(255), notnull: true
    parametros: string(255), notnull: true
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false
      updated:
        name: updated_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: false
          required: false